# Generated by Django 6.0.4 on 2026-05-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(blank=True, null=True, upload_to="photo/")),
            ],
            options={
                "verbose_name": "Karusel",
                "verbose_name_plural": "Karusellar",
            },
        ),
    ]
